spring.application.name=backend
spring.datasource.url=jdbc:mysql://localhost:3306/salesTracker
spring.datasource.username=root
spring.datasource.password=manoj@123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


jwt.secret=5678utifjhdvfedr5364758utjgnfdbvgwfr2567348596075847362456j7h54g3fg45jhk67hg5h6f45g3jh46kj75h564g53fg5uh67i5u6453ghj647ug46

# 15 min
jwt.expiration=900000

# in days
refreshtoken.expriration =15


#security
spring.mvc.throw-exception-if-no-handler-found=true
spring.web.resources.add-mappings=false

server.error.include-stacktrace=never
server.error.include-message=always